### ISSUE TITLE
Mejorar la funcionalidad de lx magx

### ISSUE THREAD

**Issue by WinnaZ** [PyAr/PyCamp_Bot#12]
1)Que le pases una lista de gente que es puede ser magx 
2)que randomize cada slot de magxs
3) que cuando cambie lx magx de turno pingee al grupo

**Comment by GuidoBattista** [comment]
Actualización de tema:
1)Que la gente se pueda anotar como mago con un "/AnotarmeComoMago"
2)"/cronogramearmagos" Randomizar Magos por slot + informar a los magos su slot + Avisar al mago cuando empiece y termine su horario
3)Que cualquiera pueda mandar "/LlamarMago", que le diga quien es el mago y que pinguee al mago
4)"/Mago?" Obtener el mago actual

**Comment by WinnaZ** [comment]
Warning: no se puede ser mago si sos responsable de un projecto en ese slot
