### ISSUE TITLE
Finalizar sistema de magos

### ISSUE THREAD

**Issue by PermisosDev** [PyAr/PyCamp_Bot#29]
* Agregar sistema aleatorio de magos.
* Agregar magos por slot
* Obtener el mago actual

**Comment by GuidoBattista** [comment]
Tema en "Mejorar la funcionalidad de lx magx #12"

**Comment by GuidoBattista** [comment]
@WinnaZ borrá este que está el "Mejorar la funcionalidad de lx magx #12"
