### ISSUE TITLE
/empiezaproyecto Avisar cuando empieza el proyecto 

### ISSUE THREAD

**Issue by GuidoBattista** [PyAr/PyCamp_Bot#46]
- "/empiezaproyecto + NOMBREPROYECTO + MENSAJEPERSONALIZADO /"(pinguee a la gente que se anotó) y avise en el grupo general que empezó. Ver si el mensaje va a ser standar y en el segundo campo poner solo el lugar o si se manda lo que escriban ahí.

**Comment by jeremyakd** [comment]
Listo, restan pruebas.
