### ISSUE TITLE
Agregarle los horarios a los slots.

### ISSUE THREAD

**Issue by GuidoBattista** [PyAr/PyCamp_Bot#47]
Cuando listea los slots te pone "A1: "A2:" Hacer que tambien ponga el horario. Ejemplo "A1 18HS:" "A2 20HS:"

**Comment by WinnaZ** [comment]
A esto le falta resolver de alguna manera la hora de almuerzo

**Comment by marcorichetta** [comment]
Podriamos agregar en este issue lo que estaba en https://github.com/PyAr/PyCamp_Bot/blob/a4fe57a0f5e09aa1fa5d1637ca669f14a7f70982/todo.md?

### Mejorar cronograma
- dentro del `/cronogramear` que te pregunte a que hora empiezan los slots de cada dia.
- guardar en la base de datos la hora real de los slots creados
- que te pregunte tambien la hora del almuerzo y que lo boquee como posibilidad

**Comment by jeremyakd** [comment]
![image](https://github.com/PyAr/PyCamp_Bot/assets/49762948/9733b0ff-2d0d-47b7-988e-659887684978)

Acomodado el mensaje.
