### ISSUE TITLE
Poder borrar proyectos

### ISSUE THREAD

**Issue by GuidoBattista** [PyAr/PyCamp_Bot#49]

**Comment by jeremyakd** [comment]
- Se corrigió el error cuando se consultaba por proyectos y no habia cargado ninguno.
- Se agregó funcionalidad para borrar proyectos(solo owner o admin).
- Se agregó normalización de naming de proyectos (lowercase).
- PR https://github.com/PyAr/PyCamp_Bot/pull/57

**Comment by jeremyakd** [comment]
Merged!
1338904da85d3c3987164f6e732d03f8a42ea6f7
